import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const HOST_ID = "cmpfewve20000wtmg0fj01t6b";

const listings = [
  {
    title: "Затишна студія в центрі Львова",
    description: "Сучасна студія з панорамним виглядом на старе місто. Поряд кафе, ресторани та головні пам'ятки. Ідеально для пар або самостійних мандрівників.",
    address: "вул. Ринок, 5",
    city: "Львів",
    country: "Україна",
    price: 45,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    propertyType: "apartment",
    amenities: ["wifi", "kitchen", "heating", "washer"],
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"],
  },
  {
    title: "Простора квартира біля моря в Одесі",
    description: "Двокімнатна квартира за 5 хвилин ходьби від пляжу Аркадія. Є балкон з видом на море, повністю обладнана кухня.",
    address: "Аркадіївський пров., 12",
    city: "Одеса",
    country: "Україна",
    price: 70,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 4,
    propertyType: "apartment",
    amenities: ["wifi", "kitchen", "balcony", "ac", "parking"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
  },
  {
    title: "Будинок у Карпатах з каміном",
    description: "Дерев'яний будинок у горах з каміном, терасою і видом на ліс. Ідеально для відпочинку від міського шуму. Поряд лижні траси та гірські маршрути.",
    address: "с. Яблуниця, вул. Гірська, 3",
    city: "Яблуниця",
    country: "Україна",
    price: 120,
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    propertyType: "house",
    amenities: ["wifi", "fireplace", "parking", "bbq", "mountain_view"],
    images: ["https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800"],
  },
  {
    title: "Мінімалістичні апартаменти в Києві",
    description: "Стильна квартира в стилі loft у Подільському районі. Висока стеля, цегляні стіни, дизайнерський інтер'єр. 10 хвилин до Контрактової площі.",
    address: "вул. Сагайдачного, 18",
    city: "Київ",
    country: "Україна",
    price: 85,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    propertyType: "apartment",
    amenities: ["wifi", "kitchen", "washer", "dryer", "ac"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
  },
  {
    title: "Вілла з басейном у Буковелі",
    description: "Розкішна вілла з приватним басейном, сауною та барбекю-зоною. Повністю укомплектована кухня, 4 спальні. Поряд найбільший гірськолижний курорт України.",
    address: "вул. Курортна, 7",
    city: "Буковель",
    country: "Україна",
    price: 350,
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 8,
    propertyType: "villa",
    amenities: ["wifi", "pool", "sauna", "bbq", "parking", "fireplace"],
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
  },
  {
    title: "Квартира-студія у Харкові",
    description: "Компактна і функціональна студія в центрі Харкова. Нова техніка, швидкий інтернет, зупинка метро за 3 хвилини ходьби.",
    address: "пл. Свободи, 4",
    city: "Харків",
    country: "Україна",
    price: 30,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    propertyType: "apartment",
    amenities: ["wifi", "kitchen", "heating", "ac"],
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800"],
  },
  {
    title: "Апартаменти з видом на замок у Кам'янці",
    description: "Унікальні апартаменти з прямим видом на Кам'янець-Подільський замок. Старовинний будинок з сучасним ремонтом у самому серці міста.",
    address: "вул. Замкова, 2",
    city: "Кам'янець-Подільський",
    country: "Україна",
    price: 55,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 4,
    propertyType: "apartment",
    amenities: ["wifi", "kitchen", "heating", "washer"],
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"],
  },
  {
    title: "Сучасний лофт у Дніпрі",
    description: "Простора квартира в стилі loft з панорамними вікнами та видом на Дніпро. Дизайнерський ремонт, smart TV, швидкий WiFi.",
    address: "Набережна Перемоги, 22",
    city: "Дніпро",
    country: "Україна",
    price: 65,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 3,
    propertyType: "apartment",
    amenities: ["wifi", "kitchen", "ac", "washer", "river_view"],
    images: ["https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800"],
  },
  {
    title: "Котедж біля озера Синевир",
    description: "Затишний котедж за 2 км від найвідомішого гірського озера Карпат. Тераса, мангал, місце для паркування. Тихе місце для сімейного відпочинку.",
    address: "с. Синевир, вул. Озерна, 8",
    city: "Синевир",
    country: "Україна",
    price: 95,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 5,
    propertyType: "house",
    amenities: ["wifi", "bbq", "parking", "fireplace", "lake_view"],
    images: ["https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800"],
  },
  {
    title: "Пентхаус у центрі Запоріжжя",
    description: "Розкішний пентхаус на останньому поверсі з терасою і панорамним видом на місто. Джакузі, смарт-система керування, консьєрж-сервіс.",
    address: "пр. Соборний, 150",
    city: "Запоріжжя",
    country: "Україна",
    price: 180,
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    propertyType: "apartment",
    amenities: ["wifi", "jacuzzi", "ac", "parking", "balcony", "city_view"],
    images: ["https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800"],
  },
  {
    title: "Будинок у виноградниках Закарпаття",
    description: "Автентичний угорський будинок серед виноградників. Дегустація місцевих вин, власний сад, тераса з гамаком. Ідеально для романтичної відпустки.",
    address: "с. Середнє, вул. Виноградна, 1",
    city: "Ужгород",
    country: "Україна",
    price: 110,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 4,
    propertyType: "house",
    amenities: ["wifi", "garden", "bbq", "parking", "wine_tasting"],
    images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800"],
  },
  {
    title: "Апартаменти поряд з Оперним театром",
    description: "Елегантні апартаменти в 2 хвилинах ходьби від Одеського оперного театру. Висока стеля, паркет, антикварні меблі поєднані з сучасною технікою.",
    address: "вул. Ланжеронівська, 10",
    city: "Одеса",
    country: "Україна",
    price: 90,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 3,
    propertyType: "apartment",
    amenities: ["wifi", "kitchen", "ac", "washer", "heating"],
    images: ["https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800"],
  },
];

async function main() {
  console.log("Seeding listings...");

  for (const data of listings) {
    await db.listing.create({
      data: {
        ...data,
        hostId: HOST_ID,
        isActive: true,
        status: "ACTIVE",
      },
    });
  }

  console.log(`Created ${listings.length} listings.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
